// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDawNEsrnm7jkk6iV1TOUY3mnjLwqiqHRk',
    appId: '1:1017044530404:web:68340f7682da3c106ee8f1',
    messagingSenderId: '1017044530404',
    projectId: 'rontohub-aff90',
    authDomain: 'rontohub-aff90.firebaseapp.com',
    storageBucket: 'rontohub-aff90.appspot.com',
    measurementId: 'G-GCBJSS6B5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTcLLTtuKTq0RJUClwZJL80dj9JxzV9mk',
    appId: '1:1017044530404:android:fc440778e54529d46ee8f1',
    messagingSenderId: '1017044530404',
    projectId: 'rontohub-aff90',
    storageBucket: 'rontohub-aff90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVIvAzlEnQCwKifPZVJHfjEPjbwHLRXjQ',
    appId: '1:1017044530404:ios:26b647b061c3d82e6ee8f1',
    messagingSenderId: '1017044530404',
    projectId: 'rontohub-aff90',
    storageBucket: 'rontohub-aff90.appspot.com',
    iosClientId: '1017044530404-t12soe8j8h3rsvoitksebq1a5dequtqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.reminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVIvAzlEnQCwKifPZVJHfjEPjbwHLRXjQ',
    appId: '1:1017044530404:ios:63d76634b20d01c06ee8f1',
    messagingSenderId: '1017044530404',
    projectId: 'rontohub-aff90',
    storageBucket: 'rontohub-aff90.appspot.com',
    iosClientId: '1017044530404-ued81udt3pcbeiujnln17asl1ksdg9of.apps.googleusercontent.com',
    iosBundleId: 'com.example.reminder.RunnerTests',
  );
}
